config/routes.rb
Rails.application.routes.draw do
  get "/about", to: "about#index"
  get "/signup", to: "user#index"
  post "/signup", to: "user#create"
  get "/login", to: "session#index"
  delete "/logout", to: "session#delete"
  post "/login", to: "session#create"
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController 
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController 
    def index
        is_logged_in = session[:user_id]
        if is_logged_in
            @users = User.all()
        end
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController 
    def index
    end

    def create
        # attempt find user
        user = User.find_by(email: login_params[:email])

        # handle user not found
        if !user.presence
            flash[:alert] = "user not found"
            render :index
            return
        end

        # attempt login
        if user.authenticate(login_params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in as #{user.name}"
        else
            flash[:alert] = "invalid email or password"
            render :index
        end
    end

    def delete
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end

    @private
    def login_params
      params.permit(:email, :password)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController 
    def index
        @user = User.new
        render :signup
    end

    def create
        @user = User.new(user_params)

        if @user.save
            # Handle successful creation
            redirect_to signup_path, notice: "User created successfully."
        else
            render :signup
        end
    end

    @private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>about</h1>

<%= Time.now%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
  <%= render partial: "shared/navbar"%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<% if flash[:notice] %>
<div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if Current.user.present? %>
    <h3>Users</h3>

    <table class="table">
    <thead>
        <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
<% else %>
    <h3>Login to view a list of users</h3>
<% end %>

app/views/session/index.html.erb
<div class="card m-5">
  <div class="card-body">


    <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
    <% end %>

            
    <%= form_with(model: @user, url: login_path, method: :post, local:true) do |form| %>
      <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control", placeholder: "Enter your email" %>
      </div>
      
      <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control", placeholder: "Enter your password" %>
      </div>
      
      <%= form.submit "Login", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>
    </div>

    <div class="d-flex align-items-center gap-2">
      <% if Current.user.present? %>
        <p style="margin-bottom: 0">Logged in as <%= Current.user.name %></p>
        <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-secondary" %>
      <% else %>
      <%= button_to "Login", login_path, method: :get, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/user/signup.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          Sign Up
        </div>
        <div class="card-body">
          <%= form_with(model: @user, url: "/signup", local:true) do |form| %>

            <div class="form-group mb-4">
              <%= form.label :name, "Name" %>
              <%= form.text_field :name, class: "form-control", placeholder: "Enter name" %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :email, "Email address" %>
              <%= form.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :password, "Password" %>
              <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
            <div class="form-group mb-4">
              <%= form.label :password_confirmation, "Confirm Password" %>
              <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
            </div>
            <%= form.submit "Sign Up", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>